server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: test-service
          uri: lb://test-service
          predicates:
            - Path=/test/** # 라우팅
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/** # 라우팅

    # Eureka 클라이언트 설정
    eureka:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/ # Eureka 서버의 주소
      instance:
        metadata-map:
          instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}} # 인스턴스 ID 설정