server:
  port: 8761  # Eureka Server 기본 포트

eureka:
  client:
    registerWithEureka: false  # Eureka 서버는 등록할 필요 없음
    fetchRegistry: false       # Eureka 서버는 레지스트리를 가져오지 않음
  server:
    enableSelfPreservation: false  # 서비스 유효성 검사 비활성화 (개발 환경용)
